'use strict';
const archiver = require('archiver');
const path = require('path');
const fs = require('fs');
const { db, UPLOADS_DIR } = require('./db');

// ─────────────────────────────────────────────────────────────────────────────
// Data helpers
// ─────────────────────────────────────────────────────────────────────────────

function getFullJobData(jobId) {
  const job = db.prepare('SELECT * FROM jobs WHERE id = ?').get(jobId);
  if (!job) return null;
  const devices = db.prepare(`
    SELECT d.*, hm.model_name, hm.model_number, hm.category as hw_category, hm.brand, hm.description as hw_description
    FROM devices d
    LEFT JOIN hardware_models hm ON d.hardware_model_id = hm.id
    WHERE d.job_id = ?
    ORDER BY d.sort_order ASC, d.created_at ASC
  `).all(jobId);
  const deviceIds = devices.map(d => d.id);
  let photos = [];
  if (deviceIds.length > 0) {
    photos = db.prepare(
      `SELECT * FROM photos WHERE device_id IN (${deviceIds.map(() => '?').join(',')}) ORDER BY sort_order ASC, created_at ASC`
    ).all(...deviceIds);
  }
  return { ...job, devices: devices.map(d => ({ ...d, photos: photos.filter(p => p.device_id === d.id) })) };
}

function loadImageDataMap(jobData) {
  const map = {};
  for (const photo of (jobData.devices || []).flatMap(d => d.photos || [])) {
    const fp = path.join(UPLOADS_DIR, photo.filename);
    if (fs.existsSync(fp)) {
      const buf = fs.readFileSync(fp);
      const ext = path.extname(photo.filename).slice(1).toLowerCase() || 'jpg';
      const mime = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
      map[photo.filename] = `data:${mime};base64,${buf.toString('base64')}`;
    }
  }
  return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Assets
// ─────────────────────────────────────────────────────────────────────────────

function getLogoSvg() {
  const candidates = [
    path.join(__dirname, '../../client/dist/logo.svg'),   // production (Docker)
    path.join(__dirname, '../../client/public/logo.svg'), // development
  ];
  for (const p of candidates) {
    try {
      const raw = fs.readFileSync(p, 'utf8');
      if (!raw) continue;
      return raw
        .replace(/<\?xml[^>]*\?>\s*/g, '')
        .replace(/<!--[\s\S]*?-->/g, '')
        .replace(/<defs>[\s\S]*?<\/defs>/g, '')   // remove <style>.st0{fill:#fff}</style>
        .replace(/class="st0"/g, 'fill="#ffffff"') // inline fill so it survives print
        .replace(/\s+/g, ' ')
        .trim();
    } catch { /* try next */ }
  }
  return '';
}

async function generateQrDataUrl(url) {
  try {
    const QRCode = require('qrcode');
    return await QRCode.toDataURL(url, {
      width: 160, margin: 1,
      color: { dark: '#0f172a', light: '#ffffff' },
      errorCorrectionLevel: 'M',
    });
  } catch { return null; }
}

// ─────────────────────────────────────────────────────────────────────────────
// CSV export
// ─────────────────────────────────────────────────────────────────────────────

function generateCsv(jobData) {
  const q = s => s ? `"${String(s).replace(/"/g, '""')}"` : '""';
  const rows = [['#','Device Name','Category','Brand','Model','Model Number','Location','Notes','Photos'].join(',')];
  (jobData.devices || []).forEach((d, i) => {
    rows.push([
      i + 1, q(d.name),
      q(d.hw_category || d.device_type || ''),
      q(d.brand || 'Verkada'),
      q(d.model_name || ''),
      q(d.model_number || ''),
      q(d.location || ''),
      q(d.notes || ''),
      (d.photos || []).length,
    ].join(','));
  });
  return rows.join('\r\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// README
// ─────────────────────────────────────────────────────────────────────────────

function generateReadme(jobData, shareUrl) {
  const totalPhotos = (jobData.devices || []).reduce((s, d) => s + (d.photos || []).length, 0);
  return `# Basic ITS — Installation Report
## ${jobData.name}

| Field | Value |
|---|---|
| **Client** | ${jobData.client || 'N/A'} |
| **Address** | ${jobData.address || 'N/A'} |
| **Contact** | ${jobData.contact_name || 'N/A'}${jobData.contact_phone ? ` (${jobData.contact_phone})` : ''} |
| **Status** | ${jobData.status} |
| **Created** | ${jobData.created_at} |
| **Devices** | ${(jobData.devices || []).length} |
| **Photos** | ${totalPhotos} |

## Files in This Archive
- \`report.html\` — Self-contained interactive installation report with embedded photos (open in any browser)
- \`devices.csv\` — Device list in CSV format (open in Excel / Google Sheets)
- \`data.json\` — Raw installation data in JSON format
- \`images/\` — Full resolution photos

## Viewing
Open \`report.html\` in any web browser. Print or Save as PDF using your browser's print function.
${shareUrl ? `\n## Live Report\nView the live report at: ${shareUrl}\n` : ''}
---
*Generated by Basic ITS Install Log*
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// HTML Report
// ─────────────────────────────────────────────────────────────────────────────

const H = s => s ? String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') : '';

function fmtDate(dt) {
  if (!dt) return '—';
  return new Date(dt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

const STATUS_LABEL = { open: 'In Progress', complete: 'Complete', archived: 'Archived' };
const STATUS_COLOR = { open: '#3b82f6', complete: '#10b981', archived: '#6b7280' };
const CAT_ICON = {
  Camera: '📷', 'Access Control': '🔒', Environmental: '🌡️',
  Intercom: '📞', Alarm: '🚨', 'Viewing Station': '🖥️', Guest: '👤', Networking: '🌐',
};

function deviceCardHtml(device, di, imageDataMap) {
  const thumbs = (device.photos || []).map((photo, pi) => {
    const src = imageDataMap[photo.filename];
    if (!src) return '';
    return `<div class="photo-thumb" onclick="lb(${di},${pi})">
        <img src="${src}" alt="${H(photo.caption || 'Photo ' + (pi + 1))}" loading="lazy"/>
        ${photo.caption ? `<p class="thumb-cap">${H(photo.caption)}</p>` : ''}
      </div>`;
  }).join('');

  const lbData = JSON.stringify((device.photos || []).map(p => ({
    src: imageDataMap[p.filename] || '',
    caption: p.caption || '',
  }))).replace(/'/g, '&#39;');

  return `
<div class="device-card avoid-break" id="device-${di}">
  <div class="dcard-header">
    <span class="dcat-icon">${CAT_ICON[device.hw_category || device.device_type] || '📦'}</span>
    <div class="dcard-title">
      <h3>${H(device.name)}</h3>
      ${device.model_name ? `<span class="dmodel-tag">${H(device.brand || 'Verkada')} ${H(device.model_name)}${device.model_number ? ` &middot; <code>${H(device.model_number)}</code>` : ''}</span>` : ''}
    </div>
    <span class="dnum-badge">#${di + 1}</span>
  </div>
  ${device.location ? `<div class="dmeta-row"><span class="dloc-pill">📍 ${H(device.location)}</span></div>` : ''}
  ${device.notes ? `<div class="dnotes">${H(device.notes)}</div>` : ''}
  ${thumbs
    ? `<div class="photos-grid" data-device="${di}" data-photos='${lbData}'>${thumbs}</div>`
    : '<p class="no-photos">No photos recorded for this device.</p>'}
</div>`;
}

async function generateReportHtml(jobData, imageDataMap, options = {}) {
  const { shareUrl = null, autoPrint = false, isLive = false } = options;
  const logoSvg = getLogoSvg();
  const qrDataUrl = shareUrl ? await generateQrDataUrl(shareUrl) : null;

  const devices = jobData.devices || [];
  const totalPhotos = devices.reduce((s, d) => s + (d.photos || []).length, 0);
  const categories = [...new Set(devices.map(d => d.hw_category || d.device_type).filter(Boolean))];
  const statusColor = STATUS_COLOR[jobData.status] || '#6b7280';
  const statusLabel = STATUS_LABEL[jobData.status] || jobData.status;
  const generatedOn = new Date().toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  const safeShareUrl = shareUrl ? H(shareUrl) : '';

  const tocHtml = devices.length > 3 ? `
<section class="toc-section">
  <h2 class="section-hd">Device Index</h2>
  <div class="toc-grid">
    ${devices.map((d, i) => `<a class="toc-item" href="#device-${i}"><span class="toc-num">${i + 1}</span><span class="toc-name">${H(d.name)}</span>${d.model_number ? `<code class="toc-model">${H(d.model_number)}</code>` : ''}</a>`).join('')}
  </div>
</section>` : '';

  const devicesHtml = devices.length
    ? `<div class="devices-list">${devices.map((d, i) => deviceCardHtml(d, i, imageDataMap)).join('')}</div>`
    : '<p class="empty-state">No devices have been recorded for this job.</p>';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Installation Report &mdash; ${H(jobData.name)} | Basic ITS</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#060f1e;--hdr:#091726;--surf:#0f2138;--surf2:#142840;
  --bdr:rgba(255,255,255,0.08);--bdr2:rgba(255,255,255,0.13);
  --tx:#dde8f5;--txm:#7a9ab5;--txd:#3d5e78;
  --acc:#3b82f6;--accl:#60a5fa;--succ:#10b981;
  --r:10px;--rlg:16px;--rsm:6px;
}
html{scroll-behavior:smooth}
body{background:var(--bg);color:var(--tx);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;line-height:1.6;font-size:15px}
a{color:var(--accl);text-decoration:none}a:hover{text-decoration:underline}
code{font-family:'SF Mono','Fira Code',monospace;font-size:0.82em;background:rgba(255,255,255,0.09);padding:.1em .35em;border-radius:4px}
.wrap{max-width:1080px;margin:0 auto;padding:0 1.5rem}

/* Action bar */
.action-bar{position:sticky;top:0;z-index:100;background:rgba(6,15,30,.93);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border-bottom:1px solid var(--bdr);padding:.55rem 0}
.ab-inner{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}
.ab-title{font-size:.82rem;color:var(--txm);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:55%}
.ab-title strong{color:var(--tx)}
.ab-btns{display:flex;gap:.4rem;flex-shrink:0}
.ab-btn{display:inline-flex;align-items:center;gap:.35rem;padding:.3rem .8rem;border-radius:9999px;font-size:.78rem;font-weight:600;cursor:pointer;border:1px solid var(--bdr2);background:rgba(255,255,255,.06);color:var(--tx);transition:all .15s;white-space:nowrap}
.ab-btn:hover{background:rgba(255,255,255,.13);border-color:rgba(255,255,255,.22)}
.ab-btn.prim{background:var(--acc);border-color:var(--acc);color:#fff}.ab-btn.prim:hover{background:#2563eb}

/* Header */
.site-header{background:linear-gradient(135deg,var(--hdr) 0%,#132a4a 100%);padding:1.4rem 0;border-bottom:1px solid var(--bdr)}
.sh-inner{display:flex;align-items:center;justify-content:space-between;gap:1rem}
.sh-logo svg{height:34px;width:auto;display:block}
.sh-badge{background:rgba(59,130,246,.15);border:1px solid rgba(59,130,246,.3);color:var(--accl);padding:.25rem .8rem;border-radius:9999px;font-size:.72rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase}

/* Cover */
.cover{background:linear-gradient(160deg,var(--hdr) 0%,#0d1e35 100%);padding:2.5rem 0 2rem;border-bottom:1px solid var(--bdr)}
.cover-grid{display:grid;grid-template-columns:1fr auto;gap:2rem;align-items:start}
@media(max-width:600px){.cover-grid{grid-template-columns:1fr}}
.job-title{font-size:1.9rem;font-weight:800;color:#fff;line-height:1.2;margin-bottom:.6rem;letter-spacing:-.02em}
.status-pill{display:inline-block;padding:.25rem .85rem;border-radius:9999px;font-size:.78rem;font-weight:700;margin-bottom:1.2rem}
.meta-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:.65rem;margin-top:.25rem}
.mc{background:rgba(255,255,255,.04);border:1px solid var(--bdr);border-radius:var(--rsm);padding:.6rem .8rem}
.mc .mc-l{font-size:.65rem;color:var(--txd);text-transform:uppercase;letter-spacing:.08em;font-weight:600}
.mc .mc-v{font-size:.88rem;color:var(--tx);font-weight:500;margin-top:.1rem}
.qr-box{background:rgba(255,255,255,.04);border:1px solid var(--bdr);border-radius:var(--r);padding:.9rem;text-align:center;min-width:160px}
.qr-box img{display:block;width:148px;height:148px;border-radius:var(--rsm);margin:0 auto;image-rendering:pixelated}
.qr-lbl{font-size:.68rem;color:var(--txm);margin-top:.45rem;line-height:1.4}
.share-url{background:rgba(255,255,255,.04);border:1px solid var(--bdr);border-radius:var(--rsm);padding:.4rem .6rem;margin-top:.3rem;font-size:.6rem;color:var(--accl);word-break:break-all;text-align:left}

/* Stats bar */
.stats-bar{background:var(--surf);padding:.85rem 0;border-bottom:1px solid var(--bdr)}
.stats-inner{display:flex;gap:.4rem;flex-wrap:wrap}
.stat-pill{display:flex;align-items:center;gap:.35rem;background:rgba(255,255,255,.05);border:1px solid var(--bdr);border-radius:9999px;padding:.35rem .9rem;font-size:.78rem;color:var(--txm)}
.stat-pill .sv{font-weight:700;color:var(--accl)}
.stat-cats{display:flex;align-items:center;gap:.35rem;flex-wrap:wrap;font-size:.75rem;color:var(--txm);padding:.35rem .9rem}

/* Main */
.main{padding:2rem 0 3rem}
.section-hd{font-size:.75rem;font-weight:700;color:var(--txm);text-transform:uppercase;letter-spacing:.1em;padding-bottom:.55rem;border-bottom:1px solid var(--bdr);margin-bottom:1.2rem;display:flex;align-items:center;gap:.5rem}
.shcount{background:var(--acc);color:#fff;font-size:.68rem;padding:.1rem .45rem;border-radius:9999px;font-weight:700}
.mb-2{margin-bottom:2rem}

/* TOC */
.toc-section{background:var(--surf);border:1px solid var(--bdr);border-radius:var(--rlg);padding:1.4rem;margin-bottom:2rem}
.toc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:.35rem;margin-top:.5rem}
.toc-item{display:flex;align-items:center;gap:.45rem;padding:.4rem .6rem;border-radius:var(--rsm);border:1px solid transparent;color:var(--txm);font-size:.83rem;transition:all .15s}
.toc-item:hover{background:rgba(59,130,246,.1);border-color:rgba(59,130,246,.2);color:var(--accl);text-decoration:none}
.toc-num{width:1.35rem;height:1.35rem;border-radius:50%;background:rgba(255,255,255,.07);display:flex;align-items:center;justify-content:center;font-size:.68rem;color:var(--txd);flex-shrink:0;font-weight:600}
.toc-name{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.toc-model{font-size:.68rem;color:var(--txd);flex-shrink:0}

/* Notes */
.notes-section{background:var(--surf);border:1px solid var(--bdr);border-left:3px solid var(--acc);border-radius:0 var(--rlg) var(--rlg) 0;padding:1.4rem;margin-bottom:2rem}
.notes-text{font-size:.88rem;white-space:pre-wrap;line-height:1.75}

/* Device cards */
.devices-list{display:flex;flex-direction:column;gap:1.2rem}
.device-card{background:var(--surf);border:1px solid var(--bdr);border-radius:var(--rlg);padding:1.4rem;transition:border-color .2s}
.device-card:hover{border-color:rgba(59,130,246,.3)}
.dcard-header{display:flex;align-items:flex-start;gap:.8rem;margin-bottom:.8rem}
.dcat-icon{font-size:1.5rem;line-height:1;flex-shrink:0;margin-top:.05rem}
.dcard-title{flex:1;min-width:0}
.dcard-title h3{font-size:1rem;font-weight:700;color:#fff;line-height:1.3}
.dmodel-tag{font-size:.76rem;color:var(--accl);display:block;margin-top:.12rem}
.dnum-badge{background:rgba(255,255,255,.06);border:1px solid var(--bdr);border-radius:9999px;padding:.12rem .55rem;font-size:.7rem;color:var(--txm);flex-shrink:0}
.dmeta-row{margin-bottom:.65rem}
.dloc-pill{font-size:.8rem;color:var(--txm)}
.dnotes{font-size:.84rem;background:rgba(255,255,255,.03);border:1px solid var(--bdr);border-left:3px solid rgba(59,130,246,.4);border-radius:0 var(--rsm) var(--rsm) 0;padding:.55rem .8rem;line-height:1.65;white-space:pre-wrap;margin-bottom:.75rem}
.no-photos{font-size:.78rem;color:var(--txd);font-style:italic;margin-top:.25rem}
.empty-state{color:var(--txm);font-style:italic;padding:1rem 0}

/* Photos */
.photos-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:.6rem;margin-top:.85rem}
.photo-thumb{cursor:pointer;border-radius:var(--rsm);overflow:hidden;background:rgba(255,255,255,.04);border:1px solid var(--bdr);transition:transform .15s,border-color .15s}
.photo-thumb:hover{transform:scale(1.02);border-color:rgba(59,130,246,.4)}
.photo-thumb img{width:100%;aspect-ratio:4/3;object-fit:cover;display:block}
.thumb-cap{font-size:.65rem;padding:.28rem .45rem;color:var(--txm);text-align:center;line-height:1.2}

/* Lightbox */
.lightbox{display:none;position:fixed;inset:0;background:rgba(0,0,0,.96);z-index:9000;flex-direction:column;align-items:center;justify-content:center;padding:1rem}
.lightbox.open{display:flex}
.lb-img{max-width:95vw;max-height:76vh;object-fit:contain;border-radius:var(--r);display:block}
.lb-cap{color:rgba(255,255,255,.75);margin-top:.7rem;font-size:.875rem;text-align:center;max-width:600px}
.lb-ctr{color:rgba(255,255,255,.4);font-size:.72rem;margin-top:.3rem}
.lb-close{position:absolute;top:1rem;right:1rem;background:rgba(255,255,255,.1);border:none;color:#fff;width:2.5rem;height:2.5rem;border-radius:50%;cursor:pointer;font-size:1.2rem;display:flex;align-items:center;justify-content:center;transition:background .15s}
.lb-close:hover{background:rgba(255,255,255,.25)}
.lb-nav{display:flex;gap:1rem;align-items:center;margin-top:.6rem}
.lb-btn{background:rgba(255,255,255,.1);border:none;color:#fff;padding:.55rem 1.2rem;border-radius:9999px;cursor:pointer;font-size:.85rem;transition:background .15s}
.lb-btn:hover{background:rgba(255,255,255,.25)}

/* Footer */
.site-footer{background:linear-gradient(135deg,var(--hdr) 0%,#091f38 100%);border-top:1px solid var(--bdr);padding:1.75rem 0;margin-top:3rem}
.footer-inner{display:flex;align-items:center;justify-content:space-between;gap:1.5rem;flex-wrap:wrap}
.footer-logo svg{height:24px;width:auto;opacity:.45;display:block}
.footer-txt{font-size:.72rem;color:var(--txd);line-height:1.6}

/* ── PRINT ───────────────────────────────────────────────────────────────── */
@media print{
  /* Force ALL elements to print backgrounds exactly */
  *{
    -webkit-print-color-adjust:exact!important;
    print-color-adjust:exact!important;
    color-adjust:exact!important;
  }
  /* Light defaults for content area */
  :root{
    --bg:#fff;--hdr:#091726;--surf:#fff;--surf2:#f8fafc;
    --bdr:#dde3ea;--bdr2:#c8d0da;
    --tx:#1e293b;--txm:#475569;--txd:#64748b;
    --acc:#2563eb;--accl:#1d4ed8;
    --r:8px;--rlg:12px;--rsm:5px;
  }
  html,body{background:#fff!important;margin:0;padding:0}
  .action-bar,.no-print,.lightbox{display:none!important}

  /* ── Dark header — preserve brand ──────────────────────── */
  .site-header{
    background-color:#091726!important;
    -webkit-print-color-adjust:exact!important;
    print-color-adjust:exact!important;
    padding:1rem 0!important;
    border-bottom:none!important;
  }
  .sh-logo svg{height:30px!important;width:auto!important;display:block!important}
  .sh-logo svg path,.sh-logo svg g{fill:#ffffff!important}
  .sh-badge{display:none!important}

  /* ── Dark cover — preserves brand, page break after ───── */
  .cover{
    background-color:#091726!important;
    -webkit-print-color-adjust:exact!important;
    print-color-adjust:exact!important;
    color:#ffffff!important;
    padding:1.75rem 0 1.5rem!important;
    border-bottom:none!important;
    page-break-after:always;
    break-after:page;
  }
  .cover .job-title{color:#ffffff!important;font-size:1.6rem!important}
  .cover .status-pill{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
  /* Replace rgba() with solid equivalents so they print */
  .cover .mc{background-color:#132a4a!important;border:1px solid #1e3d5c!important}
  .cover .mc .mc-l{color:#7aadcc!important}
  .cover .mc .mc-v{color:#ffffff!important}
  .cover .qr-box{background-color:#132a4a!important;border:1px solid #1e3d5c!important}
  .cover .qr-lbl{color:#9bbdd0!important}
  .cover .share-url{background-color:#0d2238!important;color:#60a5fa!important;border-color:#1e3d5c!important}
  .cover-grid{display:flex!important;gap:1.5rem!important;align-items:flex-start!important}

  /* ── Stats bar ──────────────────────────────────────────── */
  .stats-bar{background-color:#f1f5f9!important;border-bottom:2px solid #dde3ea!important;padding:.6rem 0!important}
  .stat-pill{background-color:#ffffff!important;border:1px solid #dde3ea!important;color:#475569!important}
  .stat-pill .sv{color:#1d4ed8!important}
  .stat-cats{color:#475569!important}

  /* ── Main content ───────────────────────────────────────── */
  .main{padding:1.5rem 0 2rem!important}
  .section-hd{color:#374151!important;border-bottom-color:#dde3ea!important}
  .shcount{background-color:#2563eb!important;color:#fff!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}

  /* ── TOC ────────────────────────────────────────────────── */
  .toc-section{background-color:#f8fafc!important;border:1px solid #dde3ea!important;page-break-inside:avoid;break-inside:avoid}
  .toc-item{color:#374151!important;border-color:transparent!important}
  .toc-num{background-color:#e2e8f0!important;color:#475569!important}
  .toc-model{color:#94a3b8!important}

  /* ── Notes ──────────────────────────────────────────────── */
  .notes-section{background-color:#f8fafc!important;border-color:#dde3ea!important;border-left:3px solid #2563eb!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
  .notes-text{color:#1e293b!important}

  /* ── Device cards ───────────────────────────────────────── */
  .devices-list{gap:.75rem!important}
  .device-card{
    background-color:#ffffff!important;
    border:1px solid #dde3ea!important;
    box-shadow:none!important;
    page-break-inside:avoid;
    break-inside:avoid;
    margin-bottom:.5rem!important;
    padding:1rem!important;
  }
  .device-card:hover{border-color:#dde3ea!important;transform:none!important}
  .dcard-title h3{color:#1e293b!important;font-size:.95rem!important}
  .dmodel-tag{color:#2563eb!important}
  .dnum-badge{background-color:#f1f5f9!important;color:#64748b!important;border-color:#dde3ea!important}
  .dloc-pill{color:#475569!important}
  .dnotes{
    background-color:#f8fafc!important;
    border-color:#dde3ea!important;
    border-left:3px solid #2563eb!important;
    -webkit-print-color-adjust:exact!important;
    print-color-adjust:exact!important;
    color:#1e293b!important;
  }
  .no-photos{color:#94a3b8!important}

  /* ── Photos ─────────────────────────────────────────────── */
  .photos-grid{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:.35rem!important;margin-top:.6rem!important}
  .photo-thumb{
    background-color:#f8fafc!important;
    border:1px solid #dde3ea!important;
    page-break-inside:avoid;
    break-inside:avoid;
  }
  .photo-thumb:hover{transform:none!important}
  .photo-thumb img{width:100%!important;height:auto!important;max-height:160px!important;object-fit:cover!important}
  .thumb-cap{color:#64748b!important;font-size:.62rem!important}

  /* ── Dark footer — preserve brand ──────────────────────── */
  .site-footer{
    background-color:#091726!important;
    -webkit-print-color-adjust:exact!important;
    print-color-adjust:exact!important;
    margin-top:1.5rem!important;
    padding:1rem 0!important;
    border-top:none!important;
  }
  .footer-logo svg{height:20px!important;width:auto!important;opacity:1!important;display:block!important}
  .footer-logo svg path,.footer-logo svg g{fill:#ffffff!important}
  .footer-txt{color:#94a3b8!important}
  .footer-txt a{color:#60a5fa!important}

  @page{margin:.65in .75in;size:letter portrait}
}

@media(max-width:600px){
  .job-title{font-size:1.4rem}
  .photos-grid{grid-template-columns:repeat(auto-fill,minmax(110px,1fr))}
  .meta-grid{grid-template-columns:1fr 1fr}
}
</style>
</head>
<body>

${isLive ? `
<div class="action-bar no-print">
  <div class="ab-inner wrap">
    <div class="ab-title"><strong>${H(jobData.name)}</strong> &mdash; Installation Report</div>
    <div class="ab-btns">
      ${safeShareUrl ? `<button class="ab-btn" onclick="copyLink()">🔗 Copy Link</button>` : ''}
      <button class="ab-btn prim" onclick="window.print()">🖨️ Print / PDF</button>
    </div>
  </div>
</div>` : ''}

<header class="site-header">
  <div class="sh-inner wrap">
    <div class="sh-logo">${logoSvg}</div>
    <span class="sh-badge">Installation Report</span>
  </div>
</header>

<section class="cover">
  <div class="wrap">
    <div class="cover-grid">
      <div>
        <h1 class="job-title">${H(jobData.name)}</h1>
        <div class="status-pill" style="background:${statusColor}22;color:${statusColor};border:1px solid ${statusColor}44">${statusLabel}</div>
        <div class="meta-grid">
          ${jobData.client ? `<div class="mc"><div class="mc-l">Client</div><div class="mc-v">${H(jobData.client)}</div></div>` : ''}
          ${jobData.address ? `<div class="mc"><div class="mc-l">Site Address</div><div class="mc-v">${H(jobData.address)}</div></div>` : ''}
          ${jobData.contact_name ? `<div class="mc"><div class="mc-l">Contact</div><div class="mc-v">${H(jobData.contact_name)}${jobData.contact_phone ? `<br/><span style="font-size:.8em;opacity:.7">${H(jobData.contact_phone)}</span>` : ''}</div></div>` : ''}
          <div class="mc"><div class="mc-l">Start Date</div><div class="mc-v">${fmtDate(jobData.created_at)}</div></div>
          ${jobData.completed_at ? `<div class="mc"><div class="mc-l">Completed</div><div class="mc-v">${fmtDate(jobData.completed_at)}</div></div>` : ''}
          <div class="mc"><div class="mc-l">Report Generated</div><div class="mc-v" style="font-size:.76rem">${H(generatedOn)}</div></div>
        </div>
      </div>
      ${qrDataUrl ? `
      <div class="qr-box">
        <img src="${qrDataUrl}" alt="QR code" width="148" height="148"/>
        <p class="qr-lbl">Scan for live report</p>
        <div class="share-url">${safeShareUrl}</div>
      </div>` : (safeShareUrl ? `
      <div class="qr-box" style="min-width:auto;max-width:220px">
        <p class="qr-lbl">Live report:</p>
        <div class="share-url">${safeShareUrl}</div>
      </div>` : '')}
    </div>
  </div>
</section>

<div class="stats-bar">
  <div class="wrap"><div class="stats-inner">
    <div class="stat-pill">Devices: <span class="sv">${devices.length}</span></div>
    <div class="stat-pill">Photos: <span class="sv">${totalPhotos}</span></div>
    <div class="stat-pill">Categories: <span class="sv">${categories.length}</span></div>
    ${categories.length ? `<div class="stat-cats">${categories.map(c => `${CAT_ICON[c] || '📦'} ${H(c)}`).join(' &nbsp;&middot;&nbsp; ')}</div>` : ''}
  </div></div>
</div>

<main class="main">
  <div class="wrap">
    ${tocHtml}
    ${jobData.notes ? `
    <section class="notes-section mb-2">
      <h2 class="section-hd">Job Notes</h2>
      <p class="notes-text">${H(jobData.notes)}</p>
    </section>` : ''}
    <h2 class="section-hd">Installed Devices <span class="shcount">${devices.length}</span></h2>
    ${devicesHtml}
  </div>
</main>

<footer class="site-footer">
  <div class="wrap"><div class="footer-inner">
    <div class="footer-logo">${logoSvg}</div>
    <div class="footer-txt">
      <div>Basic ITS Installation Report &mdash; ${H(jobData.name)}</div>
      <div>Generated ${H(generatedOn)}</div>
      ${safeShareUrl && isLive ? `<div><a href="${safeShareUrl}" style="color:var(--accl);font-size:.68rem">${safeShareUrl}</a></div>` : ''}
    </div>
  </div></div>
</footer>

<div class="lightbox no-print" id="lightbox" onclick="lbOut(event)">
  <button class="lb-close" onclick="lbClose()">&#x2715;</button>
  <img id="lb-img" class="lb-img" src="" alt=""/>
  <p id="lb-cap" class="lb-cap"></p>
  <p id="lb-ctr" class="lb-ctr"></p>
  <div class="lb-nav">
    <button class="lb-btn" onclick="lbPrev()">&#8592; Prev</button>
    <button class="lb-btn" onclick="lbNext()">Next &#8594;</button>
  </div>
</div>

<script>
(function(){
  var photos=[],idx=0;
  function lb(di,pi){
    var g=document.querySelector('[data-device="'+di+'"]');
    if(!g)return;
    try{photos=JSON.parse(g.dataset.photos);}catch(e){return;}
    idx=pi;show();
    document.getElementById('lightbox').classList.add('open');
    document.body.style.overflow='hidden';
  }
  function show(){
    var p=photos[idx];
    document.getElementById('lb-img').src=p.src;
    document.getElementById('lb-cap').textContent=p.caption||'';
    document.getElementById('lb-ctr').textContent=(idx+1)+' / '+photos.length;
  }
  function lbClose(){document.getElementById('lightbox').classList.remove('open');document.body.style.overflow='';}
  function lbNext(){idx=(idx+1)%photos.length;show();}
  function lbPrev(){idx=(idx-1+photos.length)%photos.length;show();}
  function lbOut(e){if(e.target===document.getElementById('lightbox'))lbClose();}
  function copyLink(){
    var url=${JSON.stringify(shareUrl || '')};
    if(!url)return;
    if(navigator.clipboard){
      navigator.clipboard.writeText(url).then(function(){flash();}).catch(function(){prompt('Copy:',url);});
    }else{prompt('Copy:',url);}
  }
  function flash(){
    var b=document.querySelector('.ab-btn[onclick*="copyLink"]');
    if(b){var t=b.textContent;b.textContent='✓ Copied!';b.style.color='#10b981';setTimeout(function(){b.textContent=t;b.style.color='';},2000);}
  }
  document.addEventListener('keydown',function(e){
    if(!document.getElementById('lightbox').classList.contains('open'))return;
    if(e.key==='ArrowRight')lbNext();
    else if(e.key==='ArrowLeft')lbPrev();
    else if(e.key==='Escape')lbClose();
  });
  window.lb=lb;window.lbClose=lbClose;window.lbNext=lbNext;window.lbPrev=lbPrev;window.lbOut=lbOut;window.copyLink=copyLink;
  ${autoPrint ? 'window.addEventListener("load",function(){setTimeout(function(){window.print();},600);});' : ''}
})();
</script>
</body>
</html>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

async function serveReportInline(jobId, res, shareUrl, options = {}) {
  const jobData = getFullJobData(jobId);
  if (!jobData) {
    return res.status(404).send('<html><body style="font-family:sans-serif;padding:2rem"><h2>Job not found</h2></body></html>');
  }
  const imageDataMap = loadImageDataMap(jobData);
  const html = await generateReportHtml(jobData, imageDataMap, {
    shareUrl: shareUrl || null,
    isLive: true,
    autoPrint: options.autoPrint || false,
  });
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.send(html);
}

async function exportJobAsZip(jobId, res, options = {}) {
  const jobData = getFullJobData(jobId);
  if (!jobData) throw new Error('Job not found');

  const imageDataMap = loadImageDataMap(jobData);
  const safeJobName = jobData.name.replace(/[^a-z0-9_\-\s]/gi, '_').replace(/\s+/g, '_').toLowerCase();

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="basicits_${safeJobName}_${Date.now()}.zip"`);

  const archive = archiver('zip', { zlib: { level: 6 } });
  archive.pipe(res);

  const reportHtml = await generateReportHtml(jobData, imageDataMap, {
    shareUrl: options.shareUrl || null,
    isLive: false,
  });
  archive.append(reportHtml, { name: 'report.html' });
  archive.append(generateCsv(jobData), { name: 'devices.csv' });
  archive.append(JSON.stringify(jobData, null, 2), { name: 'data.json' });
  archive.append(generateReadme(jobData, options.shareUrl || null), { name: 'README.md' });

  for (const photo of (jobData.devices || []).flatMap(d => d.photos || [])) {
    const fp = path.join(UPLOADS_DIR, photo.filename);
    if (fs.existsSync(fp)) archive.file(fp, { name: `images/${photo.filename}` });
  }

  await archive.finalize();
}

module.exports = { exportJobAsZip, serveReportInline, getFullJobData };
